### ISSUE TITLE
Add "Copy" command

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerDW/Orienteer#191]
Command should be placed on a tables with listing of ODocuments: BrowsePage and reference parameter's tables.
Command should just create a copy of an object: there is corresponding method in ODocument.
Examples where Copy should present: 
http://demo.orienteer.org/browse/OLocalization
http://demo.orienteer.org/doc/5:0 (table with roles)
and etc.

**Comment by evilsyncope** [comment]
It seems copy() method is not suitable for this purpose, because it copies identity of source entity also. So maybe it would be better to create new instance and to paste all field values from source to target.
Also there are problems with copying entities with unique indexes. E.g. roles with index by "name" property. Should we add some suffix to copied value like "copiedValue (1)" or open edit page to enter new value manually?

**Comment by PhantomYdn** [comment]
Lets have Copy functionality just for one document with switching to edit mode
